language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
before_install:
  - travis_retry gem install bundler
  - bundle --version
install:
  - travis_retry bundle install
before_script:
  - travis_retry bundle exec appraisal install
script:
  - bundle exec appraisal rake spec
